site_name: Tech Blog
site_url: https://jhqiu21.github.io/blog/
theme: 
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" # color scheme: light
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # color scheme: dark
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: octicons/sun-16
        name: Switch to system preference
  language: en
  icon:
    logo: material/earth
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - content.tabs.link
    # - navigation.tabs

nav:
  - Hello: index.md 
  - LeetCode: LeetCode/LeetCode.md


extra_css:
  - css/custom.css